server:
  port: 8088
  servlet:
    context-path: /
    session:
      cookie:
        max-age: 30m
logging:
  level:
    com.mxjlife: debug
  file:
    max-size: 50m
spring:
  http:
    encoding:
      charset: utf-8
  mail:
    host: smtp.163.com
    username: test@163.com
    password: 123456
    default-encoding: UTF-8

