server:
  port: 8089
  servlet:
    context-path: /
    session:
      cookie:
        max-age: 30m
logging:
  level:
    com.mxjlife: debug
  file:
    max-size: 50m
spring:
  http:
    encoding:
      charset: utf-8
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mail:
    host: smtp.163.com
    username: test@163.com
    password: 123456
    default-encoding: UTF-8
system:
  datasource:
    system:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: MXJ_2019_mxj
      # 最大的缓冲池大小
      maxPoolSize: 30
      # 最小闲置线程
      minIdle: 5

